#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-service
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: wdm22.group6.app
#      http:
#        paths:
#          - path: /orders/?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: order-service
#                port:
#                  number: 8081
#          - path: /stock/?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: stock-service
#                port:
#                  number: 8082
#          - path: /payment/?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: payment-service
#                port:
#                  number: 8083